version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    #container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: ruok,stat,conf
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - confluent

  broker:
    image: confluentinc/cp-server:7.4.0
    hostname: broker
    #container_name: broker
    depends_on:
      - zookeeper        
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - confluent
    command: >
      bash -c "until nc -z zookeeper 2181; do echo 'waiting for zookeeper'; sleep 2; done;
               echo 'zookeeper ready, starting broker';
               /etc/confluent/docker/run"
    healthcheck:
      test: [ "CMD", "bash", "-c", 'nc -z localhost 29092' ]
      interval: 10s
      timeout: 5s
      retries: 10
      
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    hostname: schema-registry
    #container_name: schema-registry
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    command: >
      bash -c "until nc -z zookeeper 2181; do sleep 2; done;
               until nc -z broker 29092; do sleep 2; done;
               echo 'dependencies ready, starting schema-registry';
               /etc/confluent/docker/run"
    networks:
      - confluent
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/subjects" ]
      interval: 30s
      timeout: 10s
      retries: 10

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.4.0
    hostname: control-center
    container_name: control-center
    depends_on:
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      PORT: 9021
    networks:
      - confluent
    command: >
      bash -c "until nc -z zookeeper 2181; do sleep 2; done;
               until nc -z broker 29092; do sleep 2; done;
               until curl -sf http://schema-registry:8081/ >/dev/null; do sleep 2; done;
               echo 'dependencies ready, starting control-center';
               /etc/confluent/control-center/run"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9021/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    ports:
      - "9870:9870"
    volumes:
      - hdfs-nn-data:/hadoop/dfs/name
      - ./spark-apps:/opt/spark-apps
    networks:
      - confluent

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    depends_on:
      - hdfs-namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - hdfs-dn-data:/hadoop/dfs/data
      - ./spark-apps:/opt/spark-apps
    networks:
      - confluent   
  
  
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: apache/spark:3.5.0
    hostname: spark-master
    environment:
      - SPARK_MODE=master   
      - HADOOP_USER_NAME=flavia 
      - SPARK_MASTER_HOST=spark-master 
      - SPARK_MASTER_WEBUI_PORT=8080  
      - HADOOP_USER_NAME=flavia                
    ports:
      - "7077:7077"
      - "8083:8080"    
    command: > 
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0 --port 7077 --webui-port 8080
    volumes:
    # - ./spark:/opt/spark
      - ./spark-apps:/opt/spark-apps
      - ./spark-apps/data:/opt/spark-apps/data
      # Mapeie sua pasta local de JARs para o caminho interno do container
      - ./spark/jars:/opt/spark/jars
    networks:
      - confluent
    
  spark-worker:
    image: apache/spark:3.5.0
    depends_on:
      - spark-master
    ports:
    - "8084:8081"   # opcional: remapeia UI do worker para host
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HADOOP_USER_NAME=flavia
      - SPARK_DAEMON_JAVA_OPTS=-Duser.name=flavia
      - JAVA_TOOL_OPTIONS=-Duser.name=flavia
      - HADOOP_USER_NAME=flavia  
    volumes:
    #  - ./spark:/opt/spark
      - ./spark-apps:/opt/spark-apps
      - ./spark-apps/data:/opt/spark-apps/data     
      # Mapeie sua pasta local de JARs para o caminho interno do container
      - ./spark/jars:/opt/spark/jars  
    networks:
      - confluent
    #restart: unless-stopped
    command: >
      bash -c "until bash -c '>/dev/tcp/spark-master/7077' 2>/dev/null; do echo 'waiting spark-master'; sleep 2; done;
               echo 'spark-master ready, starting worker';
               exec /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    healthcheck:
      test: ["CMD", "bash", "-c", "bash -c '>/dev/tcp/localhost/8081' 2>/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      

  airflow-db:
    image: postgres:13
    container_name: airflow-db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - confluent

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-db
    environment:
       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
       - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
       - AIRFLOW__CORE__LOAD_EXAMPLES=False
       - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
       - AIRFLOW__WEBSERVER__SECRET_KEY=supersecretkey
       - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8082
       - AIRFLOW__CORE__REMOTE_LOGGING=False
       - AIRFLOW_UID=50000
       - HADOOP_USER_NAME=flavia
       - DB_NAME=${MSSQL_DB} 
       - DB_HOST=${MSSQL_HOST}
       - DB_USER=${MSSQL_USER}
       - DB_PASS=${MSSQL_PASS}     
    ports:
      - "8082:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      # - ./spark:/opt/spark 
      - ./spark-apps:/opt/spark-apps
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hadoop-config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      #- ../dbt_analytics:/opt/airflow/dbt_project
      # Mapeie sua pasta local de JARs para o caminho interno do container
      #- ./dbt_project:/opt/airflow/dbt_project
      - ./spark/jars:/opt/spark/jars
      - /mnt/c/Flavia/github/api-kafka-dbt-pb/dbt_analytics:/opt/airflow/dbt_project
               
    networks:
      - confluent
    command: >
      bash -c "
        while ! pg_isready -h airflow-db -p 5432 -U airflow; do sleep 2; done &&
        airflow db upgrade &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
        airflow webserver"
  
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
       - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
       - AIRFLOW__CORE__LOAD_EXAMPLES=False
       - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
       - AIRFLOW__WEBSERVER__SECRET_KEY=supersecretkey
       - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8082
       - AIRFLOW__CORE__REMOTE_LOGGING=False
       - AIRFLOW_UID=50000
       - HADOOP_USER_NAME=flavia
       - DB_NAME=${MSSQL_DB} 
       - DB_HOST=${MSSQL_HOST}
       - DB_USER=${MSSQL_USER}
       - DB_PASS=${MSSQL_PASS}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark:/opt/spark
      - ./spark-apps:/opt/spark-apps
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hadoop-config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      #- ./dbt_project:/opt/airflow/dbt_project
      #- ../dbt_analytics:/opt/airflow/dbt_project
      - /mnt/c/Flavia/github/api-kafka-dbt-pb/dbt_analytics:/opt/airflow/dbt_project
      # Mapeie sua pasta local de JARs para o caminho interno do container
      - ./spark/jars:/opt/spark/jars
      
    networks:
      - confluent
    command: >
      bash -c "
        while ! airflow db check 2>/dev/null; do echo 'Waiting for DB init...'; sleep 2; done &&
        airflow scheduler"


volumes:
  postgres_data:
  hdfs-nn-data:
  hdfs-dn-data:  
 
networks:
  confluent:
    driver: bridge